### ISSUE TITLE
Calling SceneObjects.getAllSceneObjects(); wont work

### ISSUE THREAD

**Issue by naksuasd** [Parabot/Parabot-317-API-Minified#23]
java.lang.AbstractMethodError: ay.getGroundItem()Lorg/rev317/min/accessors/SceneObjectTile;
        at org.rev317.min.api.methods.SceneObjects.getSceneObjectsAtTile(SceneObjects.java:217)
        at org.rev317.min.api.methods.SceneObjects.getAllSceneObjects(SceneObjects.java:161)
        at org.naksuasd.WriteHelper.WriteHelper.loop(WriteHelper.java:34)
        at org.parabot.environment.scripts.framework.Looper.execute(Frameworks.java:32)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
        Script stopped.

**Comment by JKetelaar** [comment]
Belongs to the hooks repository. Please post it there and also define the server.
