### ISSUE TITLE
java.lang.AbstractMethodError: b.isLoggedIn()Z

### ISSUE THREAD

**Issue by dani-h** [Parabot/Parabot-317-API-Minified#25]
java.lang.AbstractMethodError: b.isLoggedIn()Z
        at strategies.Login$.activate(Login.scala:17)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Frameworks.java:55)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Thread.java:745)

Ever since the recent Ikov update.

**Comment by JKetelaar** [comment]
This is a hook issue. Please post this issue here. https://github.com/Parabot/Missing-hooks/issues
