### ISSUE TITLE
PKHonor Randoms error

### ISSUE THREAD

**Issue by Kozs** [Parabot/Parabot-317-API-Minified#44]
`java.lang.NullPointerException
        at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:21)
        at org.rev317.min.api.methods.Npcs$3.accept(Npcs.java:123)
        at org.rev317.min.api.methods.Npcs$3.accept(Npcs.java:118)
        at org.rev317.min.api.methods.Npcs.getNpcs(Npcs.java:51)
        at org.rev317.min.api.methods.Npcs.getNearest(Npcs.java:118)
        at org.parabot.randoms.b.H.activate(h:75)
        at org.parabot.environment.scripts.randoms.RandomHandler.checkAndRun(RandomHandler.java:92)
        at org.parabot.environment.scripts.Script.run(Script.java:104)
        at java.lang.Thread.run(Unknown Source)
Script stopped/finished, unloading and stopping...
Done.`

This happen while I was at home, so I assume someone else got the random and when it tried to interact, didn't work.

**Comment by Kozs** [comment]
Any progress? @JKetelaar
