### ISSUE TITLE
    at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:21)

### ISSUE THREAD

**Issue by lordgmage** [Parabot/Parabot-317-API-Minified#49]
```java.lang.NullPointerException
    at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:21)
    at org.rev317.min.api.methods.Npcs$3.accept(Npcs.java:123)
    at org.rev317.min.api.methods.Npcs$3.accept(Npcs.java:118)
    at org.rev317.min.api.methods.Npcs.getNpcs(Npcs.java:51)
    at org.rev317.min.api.methods.Npcs.getNearest(Npcs.java:118)
    at org.parabot.lord.DreamPeng.strategies.Killing.activate(Killing.java:18)
    at org.parabot.environment.scripts.framework.StrategyWorker.execute(Frameworks.java:55)
    at org.parabot.environment.scripts.Script.run(Script.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by JKetelaar** [comment]
We'll need to build an if check here: https://github.com/Parabot/Parabot-317-API-Minified/blob/master/src/main/java/org/rev317/min/api/methods/Npcs.java#L123

```
                if (npc.getDef() != null){
                    for (final int id : ids) {
                        if (id == npc.getDef().getId()) {
                            return true;
                        }
                    }
                }
```

**Comment by JKetelaar** [comment]
Could you make a PR for this @Fryslan?

**Comment by Fryslan** [comment]
done

**Comment by JKetelaar** [comment]
This should be working now, can you confirm this @lordgmage?

**Comment by JKetelaar** [comment]
Solved!
