### ISSUE TITLE
NPC getId long value

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot-317-API-Minified#69]
It sometimes happens a server has a long value for getId for NPC's.
Then this error will happen:
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    b.getNpcs()[Lorg/rev317/min/accessors/Npc; @4: checkcast
  Reason:
    Type integer (current frame, stack[0]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'b' }
    stack: { integer }
  Bytecode:
    0x0000000: 2ab4 094b c01b a4b0                    

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.rev317.min.Loader.fetchApplet(Loader.java:42)
	at org.parabot.core.Context.load(Context.java:181)
	at org.parabot.environment.servers.executers.ServerExecuter$1.run(ServerExecuter.java:28)
	at java.lang.Thread.run(Thread.java:745)
```

You can temporarly solve this by adding the `-noverify` argument, but it would be better to solve this program-wise, something like `getLongId`, whereas the default getId would check if it has a value; if it doesn't, it will take the value from getLongId and return a cast of it. 
If value is bigger (because the storage of a long can simply be bigger) throw an Exception.

**Comment by CapslockRSPS** [comment]
Solved in pr #70.
