### ISSUE TITLE
AbstractMethodError: getLongId

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot-317-API-Minified#73]
java.lang.AbstractMethodError: pkhonor.C.getLongId()J
    at org.rev317.min.api.wrappers.NpcDef.getLongId(NpcDef.java:54)
    at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:35)
    at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:21)
    at org.rev317.min.api.methods.Npcs$3.accept(Npcs.java:126)
    at org.rev317.min.api.methods.Npcs$3.accept(Npcs.java:120)
    at org.rev317.min.api.methods.Npcs.getNpcs(Npcs.java:53)
    at org.rev317.min.api.methods.Npcs.getNearest(Npcs.java:120)
    at org.parabot.randoms.pkhonor.SandwichLady.getLady(SandwichLady.java:39)
    at org.parabot.randoms.pkhonor.SandwichLady.activate(SandwichLady.java:21)
    at org.parabot.environment.randoms.RandomHandler.checkAndRun(RandomHandler.java:110)
    at org.parabot.environment.scripts.Script.run(Script.java:105)
    at java.lang.Thread.run(Thread.java:745)

**Comment by JKetelaar** [comment]
Cannot catch an `AbstractMethodError`, will have to figure out something else.

**Comment by JKetelaar** [comment]
>First get the desc of the field, then call the appropriate method.
